// Core exports
export { FynixFactory } from "./core/fynix-factory";
export { FynixApplication } from "./core/fynix-application";
export { Container } from "./core/container";
export { ModuleContainer } from "./core/module-container";
export { HotReloadOptions } from "./core/hot-reload";

// Decorators
export { Controller } from "./decorators/controller.decorator";
export {
  Get,
  Post,
  Put,
  Delete,
  Patch,
  Options,
  Head,
} from "./decorators/http-methods.decorator";
export { Injectable } from "./decorators/injectable.decorator";
export { Module } from "./decorators/module.decorator";
export { Entity } from "./decorators/entity.decorator";
export {
  Column,
  PrimaryGeneratedColumn,
  Index,
  Unique,
  ForeignKey,
} from "./decorators/column.decorator";
export {
  Param,
  Query,
  Body,
  Headers,
  Req,
  Res,
} from "./decorators/params.decorator";
export { UseGuards } from "./decorators/guards.decorator";
export { UseInterceptors } from "./decorators/interceptors.decorator";
export { UsePipes } from "./decorators/pipes.decorator";

// Interfaces and Common
export * from "./common/interfaces";

// Export built-in features
export {
  DatabaseService,
  SecurityService,
  JwtAuthGuard,
  CorsInterceptor,
  SecurityHeadersInterceptor,
  RateLimitInterceptor,
  StaticFilesInterceptor,
  QueryBuilder,
  Repository,
  BaseEntity,
  SchemaSyncService,
  Logger,
  GlobalExceptionFilter,
  LoggingInterceptor,
  // Validation
  ValidationPipe,
  ValidationService,
  ValidationException,
  validate,
  IsString,
  IsNumber,
  IsInt,
  IsBoolean,
  IsEmail,
  IsURL,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsIn,
  IsDate,
  IsArray,
  IsObject,
  IsOptional,
  // Exception Filters
  HttpException,
  BadRequestException,
  UnauthorizedException,
  ForbiddenException,
  NotFoundException,
  MethodNotAllowedException,
  NotAcceptableException,
  RequestTimeoutException,
  ConflictException,
  GoneException,
  PayloadTooLargeException,
  UnsupportedMediaTypeException,
  UnprocessableEntityException,
  TooManyRequestsException,
  InternalServerErrorException,
  NotImplementedException,
  BadGatewayException,
  ServiceUnavailableException,
  GatewayTimeoutException,
  ExceptionFilter,
  Catch,
  HttpExceptionFilter,
  AllExceptionsFilter,
  ExceptionHandler,
  // File Upload
  FileUploadService,
  FileUploadInterceptor,
  UploadedFile,
  UploadedFiles,
  getFileUploadMetadata,
  // Pagination
  PaginationService,
  PaginationInterceptor,
  PaginationPipe,
  PaginationHelper,
  Paginate,
  createPaginatedResponse,
  // Configuration
  ConfigService,
  createConfig,
  getConfig,
  ConfigProperty,
  // Compression
  CompressionInterceptor,
  shouldCompress,
  gzipCompress,
  deflateCompress,
  gzipDecompress,
  deflateDecompress,
  // Transactions (Phase 2)
  Transaction,
  TransactionManager,
  TransactionHelper,
  InjectTransaction,
  getTransactionConnection,
  // Transform Pipes (Phase 2)
  ParseIntPipe,
  ParseFloatPipe,
  ParseBoolPipe,
  ParseArrayPipe,
  ParseUUIDPipe,
  ParseDatePipe,
  ParseEnumPipe,
  ParseJsonPipe,
  DefaultValuePipe,
  PipeChain,
  chain,
  // Security (Phase 3)
  CsrfInterceptor,
  CsrfDoubleSubmitInterceptor,
  generateCsrfToken,
  SanitizeHtmlPipe,
  Sanitize,
  SqlSanitizePipe,
  SanitizationService,
  WhitelistPipe,
  BlacklistPipe,
  TrimPipe,
  LowercasePipe,
  UppercasePipe,
  ApiKeyGuard,
  ScopedApiKeyGuard,
  ApiKeyService,
  InMemoryApiKeyStore,
  AdvancedRateLimitInterceptor,
  SlidingWindowRateLimiter,
  InMemoryRateLimitStore,
  RedisRateLimitStore,
  createRedisStore,
  createMemoryStore,
  // Testing (Phase 4)
  Test,
  TestingModule,
  MockRequest,
  MockResponse,
  TestClient,
  createTestClient,
  DatabaseTestHelper,
  RepositoryTestHelper,
  TestDataFactory,
  createDatabaseTestHelper,
  createRepositoryTestHelper,
  createTestDataFactory,
  expect,
  Expect,
  assertions,
  ResponseAssertions,
  // Migrations & Seeders (Phase 5)
  Migration,
  MigrationRunner,
  MigrationLoader,
  MigrationGenerator,
  createMigrationRunner,
  Seeder,
  SeederRunner,
  SeederLoader,
  SeederGenerator,
  DatabaseSeeder,
  createSeederRunner,
  createDatabaseSeeder,
  OneToOne,
  OneToMany,
  ManyToOne,
  ManyToMany,
  SoftDelete,
  RelationType,
  getRelations,
  usesSoftDelete,
  RelationLoader,
  SoftDeleteHelper,
  // API Versioning (Phase 6)
  ApiVersion,
  getApiVersion,
  isVersionDeprecated,
  VersionExtractor,
  VersionManager,
  VersionInterceptor,
  createVersionManager,
  createVersionInterceptor,
  // OpenAPI/Swagger (Phase 6)
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiQuery,
  ApiBearerAuth,
  ApiProperty,
  OpenAPIBuilder,
  SwaggerUI,
  createOpenAPIBuilder,
  // Documentation (Phase 6)
  DocumentationGenerator,
  createDocumentationGenerator,
  // CLI (Phase 6)
  FynixCli,
  createCli,
  GenerateMigrationCommand,
  RunMigrationsCommand,
  RollbackMigrationsCommand,
  ResetMigrationsCommand,
  MigrationStatusCommand,
  GenerateSeederCommand,
  RunSeedersCommand,
  GenerateControllerCommand,
  GenerateServiceCommand,
  GenerateModuleCommand,
  GenerateGuardCommand,
  // WebSocket & Real-time (Phase 7)
  WebSocketConnection,
  WebSocketGateway,
  SubscribeMessage,
  WebSocketServer,
  SSEConnection,
  Sse,
  createWebSocketServer,
  // Caching (Phase 8)
  CacheStore,
  InMemoryCacheStore,
  RedisCacheStore,
  CacheManager,
  Cache,
  CacheEvict,
  CacheInterceptor,
  ETagGenerator,
  createCacheManager,
  createInMemoryCache,
  createRedisCache,
  // Background Jobs (Phase 9)
  JobQueue,
  JobStatus,
  Job,
  Processor,
  Process,
  CronScheduler,
  Cron,
  createJobQueue,
  createCronScheduler,
  // OAuth & 2FA (Phase 10)
  OAuth2Server,
  GrantType,
  TwoFactorAuth,
  SocialAuthService,
  SocialProvider,
  createOAuth2Server,
  createSocialAuthService,
  // Performance & Monitoring (Phase 11)
  PerformanceMonitor,
  PerformanceInterceptor,
  HealthCheckService,
  HealthIndicator,
  DatabaseHealthIndicator,
  DiskSpaceHealthIndicator,
  MemoryHealthIndicator,
  PrometheusExporter,
  ClusterManager,
  createPerformanceMonitor,
  createHealthCheckService,
  createPrometheusExporter,
  createClusterManager,
  // GraphQL (Phase 12)
  Resolver,
  Query as GraphQLQuery,
  Mutation,
  Field,
  Args,
  GraphQLSchemaBuilder,
  GraphQLExecutor,
  GraphQLHandler,
  createGraphQLSchema,
  createGraphQLExecutor,
  createGraphQLHandler,
} from "./builtin";

// Metadata
export { Scope } from "./core/metadata";
